/*
 * The MIT License
 *
 * Copyright 2015 prog-labs.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui;

import comunication.ServerComunicator;
import execution.Function;
import execution.Order;
import identity.Salon;
import identity.ServerComputer;
import international.LanguagesController;
import java.io.IOException;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Sampedro
 * @version 0.2.0
 */
public class SalonsGUI extends javax.swing.JFrame {

    private static final ImageIcon icono = new ImageIcon("imagenes/Aton32.png");
    private static ArrayList<SalonPanel> salonPanels;

    public static final String PROP_ICONO = "icono";

    /**
     * Get the value of icono
     *
     * @return the value of icono
     */
    public static ImageIcon getIcono() {
        return icono;
    }

    private ArrayList<Salon> salones;

    /**
     * Creates new form InterfazSalon
     */
    private SalonsGUI() {
        initComponents();
    }

    public SalonsGUI(ArrayList<Salon> salones) {
        salonPanels = new ArrayList();
        this.salones = salones;
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtPestañas = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRooms = new javax.swing.JMenu();
        menuSelection = new javax.swing.JMenu();
        btnNotify = new javax.swing.JMenuItem();
        btnShutdown = new javax.swing.JMenuItem();
        btnSendBashOrder = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        btnHelp = new javax.swing.JMenuItem();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(LanguagesController.getWord("AppName"));
        setIconImage(getIconImage());
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        for (Salon salon : salones) {
            gui.SalonPanel interfaz = new gui.SalonPanel(salon);
            interfaz.setVisible(true);
            salonPanels.add(interfaz);
            jtPestañas.addTab(salon.getName(), interfaz);
        }

        getContentPane().add(jtPestañas);

        menuRooms.setMnemonic('R');
        menuRooms.setText(LanguagesController.getWord("Rooms"));
        jMenuBar1.add(menuRooms);

        menuSelection.setMnemonic('S');
        menuSelection.setText(LanguagesController.getWord("Selection")
        );

        btnNotify.setText(LanguagesController.getWord("Notify"));
        btnNotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotifyActionPerformed(evt);
            }
        });
        menuSelection.add(btnNotify);

        btnShutdown.setText(LanguagesController.getWord("Shutdown"));
        menuSelection.add(btnShutdown);

        btnSendBashOrder.setText(LanguagesController.getWord("Send bash order"));
        menuSelection.add(btnSendBashOrder);

        jMenuBar1.add(menuSelection);

        menuHelp.setMnemonic('H');
        menuHelp.setText(LanguagesController.getWord("Help"));

        btnHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        btnHelp.setText(LanguagesController.getWord("Help"));
        menuHelp.add(btnHelp);

        btnAbout.setText(LanguagesController.getWord("About"));
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        menuHelp.add(btnAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        AboutGUI interfazAcercaDe = new AboutGUI();
        interfazAcercaDe.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifyActionPerformed
        // TODO add your handling code here:
        ArrayList<ServerComputer> selectedComputers = getSelectedComputers();
        if(selectedComputers.isEmpty()){
            JOptionPane.showMessageDialog(this, LanguagesController.getWord("No computer selected"), LanguagesController.getWord("Error"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        String message = JOptionPane.showInputDialog(this, LanguagesController.getWord("NotifyRequest"), LanguagesController.getWord("Notify"), JOptionPane.QUESTION_MESSAGE);
        for(ServerComputer computer: selectedComputers){
            if(!computer.isPoweredOn()){
                logs.LogCreator.addToLog(logs.LogCreator.ERROR, LanguagesController.getWord("Computer") + " " + computer.getComputerNumber() + " " + LanguagesController.getWord("off"));
                continue;
            }
            if(!computer.isUsed()){
                logs.LogCreator.addToLog(logs.LogCreator.ERROR, LanguagesController.getWord("Computer") + " " + computer.getComputerNumber() +  " " + LanguagesController.getWord("not used"));
                continue;
            }
            try {
                ServerComunicator.sendObject(new Order(Function.NOTIFICACION_ORDER(computer.getUsers().get(0), message)), computer.getIP());
            } catch (SocketException ex) {
                Logger.getLogger(SalonsGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SalonsGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNotifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalonsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalonsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnHelp;
    private javax.swing.JMenuItem btnNotify;
    private javax.swing.JMenuItem btnSendBashOrder;
    private javax.swing.JMenuItem btnShutdown;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jtPestañas;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuRooms;
    private javax.swing.JMenu menuSelection;
    // End of variables declaration//GEN-END:variables

    private ArrayList<ServerComputer> getSelectedComputers() {
        ArrayList<ServerComputer> selectedComputers = new ArrayList();
        for (SalonPanel salonPanel: salonPanels){
            selectedComputers.addAll(salonPanel.getSelectedComputers());
        }
        return selectedComputers;
    }
}
